debug = true
addr = "0.0.0.0"
port = ":6666"
rpcPort = ":9527"
isMonitor = true

[log]
path = "./logs/light.log"
encoder = "json"

[mysql]
[mysql.write]
addr = ""
port = "3306"
user = "root"
pwd = "123456"
name = "light"
maxIdleCoon = 50
maxOpenCoon = 500

[email]
website = ""
user = ""
nickName = "Shine World"
pwd = ""
logo = ""